FROM openjdk:11-jre-slim

USER root

# Install Python and required packages
RUN apt-get update && \
    apt-get install -y \
    python3-pip \
    python3-dev \
    python3-venv \
    gcc \
    libc-dev \
    libpq-dev \
    wget \
    && rm -rf /var/lib/apt/lists/* \
    && python3 -m venv /opt/venv \
    && . /opt/venv/bin/activate \
    && pip install --no-cache-dir \
    pandas \
    psycopg2-binary \
    pyspark==3.1.2

# Install Spark
RUN wget https://archive.apache.org/dist/spark/spark-3.1.2/spark-3.1.2-bin-hadoop3.2.tgz \
    && tar xvf spark-3.1.2-bin-hadoop3.2.tgz \
    && mv spark-3.1.2-bin-hadoop3.2 /opt/spark \
    && rm spark-3.1.2-bin-hadoop3.2.tgz

# Install Hadoop
RUN wget https://archive.apache.org/dist/hadoop/common/hadoop-3.2.1/hadoop-3.2.1.tar.gz \
    && tar xvf hadoop-3.2.1.tar.gz \
    && mv hadoop-3.2.1 /opt/hadoop \
    && rm hadoop-3.2.1.tar.gz

# Install Spark Excel and PostgreSQL dependencies
RUN wget https://repo1.maven.org/maven2/com/crealytics/spark-excel_2.12/3.3.1_0.18.7/spark-excel_2.12-3.3.1_0.18.7.jar -P /opt/spark/jars/ && \
    wget https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.0/postgresql-42.5.0.jar -P /opt/spark/jars/

# Add Hadoop binaries to PATH
ENV HADOOP_HOME=/opt/hadoop
ENV PATH=$PATH:$HADOOP_HOME/bin:$HADOOP_HOME/sbin

# Set environment variables
ENV SPARK_HOME=/opt/spark
ENV PATH=$SPARK_HOME/bin:$PATH
ENV PYTHONPATH=$SPARK_HOME/python:$SPARK_HOME/python/lib/py4j-0.10.9.5-src.zip:$PYTHONPATH

# Configure Spark worker
ENV SPARK_WORKER_WEBUI_PORT=8081
ENV SPARK_WORKER_LOG=/spark/logs
ENV SPARK_MASTER=spark://spark-master:7077

EXPOSE 8081

# Use a non-root user
RUN groupadd -r spark && useradd -r -g spark spark
RUN mkdir -p /spark/logs /opt/spark/work && chown -R spark:spark /spark /opt/spark/work
USER spark

CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://spark-master:7077"]